# Generated by Django 4.0.2 on 2022-04-18 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programbuddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
