# Generated by Django 4.0.2 on 2022-04-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuddy_app', '0006_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/default-pic.png', null=True, upload_to=''),
        ),
    ]
