# Generated by Django 4.0.2 on 2022-04-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuddy_app', '0007_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='user',
        ),
        migrations.AddField(
            model_name='language',
            name='user_profile',
            field=models.ManyToManyField(to='programbuddy_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('FM', 'Female'), ('ML', 'Male'), ('PF', 'Prefer not to say')], default='PF', max_length=2),
        ),
    ]
