# Generated by Django 4.0.2 on 2022-04-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programbuddy_app', '0010_rename_language_language_language_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
