# Generated by Django 3.2.13 on 2022-04-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuddy_app', '0012_userprofile_language_userprofile_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-pic.png', null=True, upload_to=''),
        ),
    ]
