# Generated by Django 3.2.13 on 2022-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuddy_app', '0016_alter_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Java', 'Java'), ('C#', 'C#'), ('C++', 'C++'), ('PHP', 'PHP'), ('Swift', 'Swift')], default='JavaScript', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='proficiency',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginner', 'Beginner')], default='Beginner', max_length=20),
        ),
    ]
