# Generated by Django 3.2.13 on 2022-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programbuddy_app', '0017_auto_20220425_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Pref')], default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('Python', 'Python'), ('Java', 'Java'), ('C#', 'Csharp'), ('C++', 'Cplus'), ('PHP', 'Php'), ('Swift', 'Swift')], default='JavaScript', max_length=20),
        ),
    ]
